- hosts: localhost
  connection: local
  tasks:
     - debug:
         msg: "before we run our role"

     - import_role:
         name: snapshot

     - debug:
         msg: "after we run our role"


         #- import_role:
          #name: snapshot

          # - name: "just execute a ls -lrt command"
          # shell: "ls -lrt"
          #register: "output"

          #- debug: var=output.stdout_lines
