---
- name: Gather Diagnostics
  hosts: all
  become: false
  serial: "{{ howmany|default(1)|int }}"
  vars:
    destination_dir: "diagnostics/{{ ansible_facts['default_ipv4']['address'] }}"

  tasks:

    - name: "Create tmp storage dir"
      local_action: file path={{ destination_dir }} state=directory
      become: false

    ##Retrive cassandra files###
    - name: Fetch cassandra files
      fetch:
        src: "{{ item }}"
        dest: "{{ destination_dir }}/"
        flat: yes
      with_items:
        - "/etc/dse/cassandra/cassandra.yaml"
        - "/etc/dse/cassandra/cassandra-env.sh"
        - "/etc/dse/dse.yaml"
    ## Retrive cassandra files###



    ### Register command output####

    - name: Register Output 
      command: "{{ item }}"
      with_items:
        - "java -version" 
        - "free -m" 
        - "df -h" 
        - "/usr/bin/nodetool status" 
        - "/usr/bin/nodetool info" 
        - "/usr/bin/nodetool cfstats" 
        - "/usr/bin/nodetool tablestats" 
        - "/usr/bin/nodetool compactionstats" 
        - "/usr/bin/nodetool describecluster" 
        - "/usr/bin/nodetool gossipinfo" 
        - "/usr/bin/nodetool proxyhistograms" 
        - "/usr/bin/nodetool netstats" 
        - "/usr/bin/nodetool tpstats" 
        - "/bin/dsetool ring" 
        - "/bin/dsetool status" 
      register: output 
      #    - debug: msg="{{ free.results[0].stdout }}"

    - local_action: copy content={{ output.results[0].stderr }} dest={{ destination_dir }}/java_version.txt
    - local_action: copy content={{ output.results[1].stdout }} dest={{ destination_dir }}/free.txt
    - local_action: copy content={{ output.results[2].stdout }} dest={{ destination_dir }}/df.txt
    - local_action: copy content={{ output.results[3].stdout }} dest={{ destination_dir }}/nodetool_status.txt
    - local_action: copy content={{ output.results[4].stdout }} dest={{ destination_dir }}/info.txt
    - local_action: copy content={{ output.results[5].stdout }} dest={{ destination_dir }}/cfstats.txt
    - local_action: copy content={{ output.results[6].stdout }} dest={{ destination_dir }}/tablestats.txt
    - local_action: copy content={{ output.results[7].stdout }} dest={{ destination_dir }}/compactionstats.txt
    - local_action: copy content={{ output.results[8].stdout }} dest={{ destination_dir }}/describecluster.txt
    - local_action: copy content={{ output.results[9].stdout }} dest={{ destination_dir }}/gossipinfo.txt
    - local_action: copy content={{ output.results[10].stdout }} dest={{ destination_dir }}/proxyhistograms.txt
    - local_action: copy content={{ output.results[11].stdout }} dest={{ destination_dir }}/netstats.txt
    - local_action: copy content={{ output.results[12].stdout }} dest={{ destination_dir }}/tpstats.txt
    - local_action: copy content={{ output.results[13].stdout }} dest={{ destination_dir }}/ring.txt
    - local_action: copy content={{ output.results[14].stdout }} dest={{ destination_dir }}/dse_status.txt

    ## Gather system logs ####
    - name: Find system logs -20d
      find:
        paths: /var/log/cassandra
        patterns: 'system.log*,output.log*,debug.log*'
        age: "-20d"
      register: newer_files

    - set_fact:
        files_to_copy: "{{ newer_files.files | map(attribute='path') | list }}"

    - name: copy logs
      fetch:
        src: "{{ item }}"
        msg: "{{ item }}"
        dest: "{{ destination_dir }}/"
        flat: yes
      loop: "{{ files_to_copy }}"
     ### Gather system logs ####
